# Generated by Django 5.0.6 on 2024-10-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_book_author_remove_book_genre_delete_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
    ]
